<?php
/* $Id: phpcaptcha.install,v 1.2.4.2.2.3.2.2 2009/07/28 15:39:20 robloach Exp $ */

/**
 * @file
 * Provides install, updated, and uninstall functions for phpcaptcha.
 */

/**
 * Implementation of hook_uninstall().
 */
function phpcaptcha_uninstall() {
  // Delete all the phpcaptcha variables and then clear the variable cache  
  db_query("delete from {variable} where name like '%s'", 'phpcaptcha_%');
  cache_clear_all('variables', 'cache');
}
