    $class = 'form-module-submit-enabled';

    $xsl =  '<?xml version="1.0" encoding="ISO-8859-1"?>';
    $xsl .= '<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">';
    $xsl .= '<xsl:template match="/">';
    $xsl .= '<link href="'.drupal_get_path('module', 'cacure_mgmt').'/css/management-ajax-default.css" media="all" rel="stylesheet" type="text/css"/>';
    $xsl .= '<div class="quest-title">';
    $xsl .= '<xsl:for-each select="modules/module">';
    $xsl .=     '<xsl:if test="@id=\''.$id.'\'">';
    $xsl .=         '<xsl:if test="@status=\'submitted\'"><div class="quest-submitted image"><img src="' . $base_path . drupal_get_path('module', 'cacure_mgmt').'/image/progress-health.png"/></div></xsl:if>';
    $xsl .=         '<xsl:if test="@status=\'in-progress\'"><div class="quest-progress image"><img src="' . $base_path . drupal_get_path('module', 'cacure_mgmt').'/image/progress-health.png"/></div></xsl:if>';
    $xsl .=         '<xsl:if test="@status=\'new\'"><div class="quest-new image"><img src="' . $base_path . drupal_get_path('module', 'cacure_mgmt').'/image/new-health.png"/></div></xsl:if>';
    $xsl .=     '</xsl:if>';
    $xsl .= '</xsl:for-each>';
    $xsl .= '<p>'.t('My Questionnaire - Available NOW').'</p></div>';
    $xsl .= '<div class="quest-help">'.t("You are almost finished with this Quarterly Report Section. Once you submit this one you will be able to fill out your next available Quarterly Report Section.").'</div>';
    $xsl .=     '<div class="health-element">';
    $xsl .=         '<xsl:for-each select="modules/module">';
    $xsl .=             '<xsl:if test="@id=\''.$id.'\'">';
    $xsl .=             '<xsl:if test="@status=\'SUBMITTED\'">';
    $xsl .=               '<a href="' . $base_path . '/files/pdf" >' . t('View') . '</a>';
    $xsl .=             '</xsl:if>';
    $xsl .=                 '<div class="element-header">';
    $xsl .=                     '<div class="module-name"><xsl:value-of select="@name"/></div>';
    $xsl .=                     '<div class="status-help">';
    $xsl .=                     '<div class="status-progress"><img src="' . $base_path . drupal_get_path('module', 'cacure_mgmt').'/image/progress.png"/>'.t(" - in progress").'</div>';
    $xsl .=                     '<div class="status-finished"><img src="' . $base_path . drupal_get_path('module', 'cacure_mgmt').'/image/finish.png"/>'.t(' - finished').'</div>';
    $xsl .=                     '</div>';
    $xsl .=                 '</div>';
    $xsl .=                 '<div class="form-element-list">';
    $xsl .=                 '<xsl:for-each select="form">';
    $xsl .=                     '<div class="form-element">';
    $xsl .=                     '<xsl:if test=\'@status="new"\'><div class="form-new image"><img src="' . $base_path . drupal_get_path('module', 'cacure_mgmt').'/image/progress.png"/></div><div class="text"><xsl:value-of select="@name"/></div></xsl:if>';
    $xsl .=                     '<xsl:if test=\'@status="in-progress"\'><div class="in-progress image"><img src="' . $base_path . drupal_get_path('module', 'cacure_mgmt').'/image/progress.png"/></div><div class="text"><xsl:value-of select="@name"/></div></xsl:if>';
    $xsl .=                     '<xsl:if test=\'@status="submitted"\'><div class="submitted image"><img src="' . $base_path . drupal_get_path('module', 'cacure_mgmt').'/image/progress.png"/></div><div class="text"><xsl:value-of select="@name"/></div></xsl:if>';
    $xsl .=                     '<xsl:if test=\'@status="COMPLETED"\'><div class="completed image"><img src="' . $base_path . drupal_get_path('module', 'cacure_mgmt').'/image/finish.png"/></div><div class="text"><xsl:value-of select="@name"/></div></xsl:if>';
    $xsl .=                     '<div class="edit">';
    $xsl .= '                       <xsl:element name="a" >';
    $xsl .= '                           <xsl:attribute name="href">' . $base_path . 'editform/<xsl:value-of select="@id"/></xsl:attribute>';
    $xsl .= '                           <xsl:attribute name="class"><xsl:value-of select=\'@id\'/></xsl:attribute>';
    $xsl .=                             t('Edit >');
    $xsl .= '                       </xsl:element>';
    $xsl .=                     '</div>';
    $xsl .=                     '</div>';
    $xsl .=                 '</xsl:for-each>';
    $xsl .=                 '</div>';
    $xsl .=                 '<form id="cacure-submit-form" action="' . $base_path  . 'management/submitmodule" method="post"><input type="hidden" value="'. $id .'" id="edit-cacure-mail-form" name="form_id" /></form>';
    $xsl .=                 '<span class="form-submit form-module-submit ' . $class . '"></span>';
    $xsl .=             '</xsl:if>';
    $xsl .=         '</xsl:for-each>';
    $xsl .=     '</div>';
    $xsl .= '</xsl:template>';
    $xsl .= '</xsl:stylesheet>';
